### ISSUE TITLE
Vagrant box doesn't function OOTB 

### ISSUE THREAD

**Issue by samhavens** [dwyl/learn-elasticsearch#17]
OSX 10.11.4
Vagrant 1.8.4
vbox-img 5.0.18r106667

I had to ssh into the vagrant box, 

``` sh
sudo mkdir /var/run/elasticsearch
sudo service start elasticsearch
```

and then it worked.

**Comment by samhavens** [comment]
I would edit the Vagrantfile and submit a PR, but I don't have much Vagrant experience and don't know where the command would go.

**Comment by odannyc** [comment]
Created PR #18

**Comment by samhavens** [comment]
@odannyc This may also need `sudo mkdir /var/run/elasticsearch` before starting elasticsearch.

**Comment by RaedsLab** [comment]
Still an issue: 
I needed to do the following : 
- Start ES on boot : `sudo update-rc.d elasticsearch defaults `
- Edited `/etc/init.d/elasticsearch` like the following :
```yml
PID_DIR="/var/run"
```

**Comment by nelsonic** [comment]
@RaedsLab a PR with the fix you have devised would be _very_ much appreciated! 👍

**Comment by nelsonic** [comment]
Fixed in: https://github.com/dwyl/learn-elasticsearch/commit/b5f61167801214df1932842391697cb0cf010745
